name: A usage example

on: push

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: ./
        with:
          version: 0.18.0

      - run: ls -la /opt/hostedtoolcache/buf/0.18.0/x86_64/

      - run: buf -h
